name: Update target data

permissions:
  contents: write
  
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Update target data'
        required: false
  # schedule:
  #   - cron: '00 12 * * 3'

jobs:
  update-target-data:
    runs-on: ubuntu-22.04 
      
    steps:    
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup R 
        uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
          use-public-rspm: true
          
      - name: Install ubuntu deps
        run: |
          sudo apt-get install libcurl4-openssl-dev
          
      - name: Install dependencies
        shell: Rscript {0}
        run: |
          install.packages(c("httr","dplyr","lubridate","readr","MMWRweek","curl","here"))
          
      - name: Generate target csv file
        run:  |
          cd src
          # make sure the folder exists
          mkdir -p ../target-data
          Rscript get_target_data.R
          
      # - name: Generate time-series and oracle-output
      #   run:  |
      #     cd src
      #     Rscript get_target_data_hubverse.R
          
      - name: Commit report
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Automated data pull" || echo "No changes to commit"
          git push
